// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://erchfmxpgtmseuwuomoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyY2hmbXhwZ3Rtc2V1d3VvbW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODA2MDksImV4cCI6MjA3MTE1NjYwOX0.hmHFqw1KgJIYXTAwyuzJ-nLu70wUHEPVD2OtUgyHqrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);